@extends('admin.layouts.app')

@section('content')
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0">Create New Video Lecture</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="#">Home</a></li>
          <li class="breadcrumb-item"><a href="{{ route('video.index') }}">Video Lectures</a></li>
          <li class="breadcrumb-item active">Create</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>

<section class="content">
  <div class="card">
    <div class="card-header">
      <h3 class="card-title">Add New Video Lecture</h3>
    </div>
    <!-- /.card-header -->

    <!-- form start -->
    <form enctype="multipart/form-data" action="{{ route('video.store') }}" method="post">
      @csrf

      <div class="card-body">
        <!-- Video ID is typically auto-generated by the database, so it's not usually included in the form -->

        <div class="mb-3">
          <label for="sub_id" class="form-label h7">Subject ID</label>
          <input value="{{ old('sub_id') }}" type="text" class="form-control form-control-lg @error('sub_id') is-invalid @enderror" placeholder="Enter Subject ID" name="sub_id" id="sub_id">
          @error('sub_id')
            <p class="invalid-feedback">{{ $message }}</p>
          @enderror
        </div>

        <div class="mb-3">
          <label for="title" class="form-label h7">Title</label>
          <input value="{{ old('title') }}" type="text" class="form-control form-control-lg @error('title') is-invalid @enderror" placeholder="Enter Title" name="title" id="title">
          @error('title')
            <p class="invalid-feedback">{{ $message }}</p>
          @enderror
        </div>

        <div class="mb-3">
          <label for="video_file_name" class="form-label h7">Video File</label>
          <input type="file" class="form-control form-control-lg @error('video_file_name') is-invalid @enderror" name="video_file_name" id="video_file_name">
          @error('video_file_name')
            <p class="invalid-feedback">{{ $message }}</p>
          @enderror
        </div>

        <div class="mb-3">
          <label for="created_on" class="form-label h7">Created On</label>
          <input type="date" class="form-control form-control-lg @error('created_on') is-invalid @enderror" name="created_on" id="created_on" value="{{ old('created_on') }}">
          @error('created_on')
            <p class="invalid-feedback">{{ $message }}</p>
          @enderror
        </div>

        <div class="mb-3">
          <label for="updated_on" class="form-label h7">Updated On</label>
          <input type="date" class="form-control form-control-lg @error('updated_on') is-invalid @enderror" name="updated_on" id="updated_on" value="{{ old('updated_on') }}">
          @error('updated_on')
            <p class="invalid-feedback">{{ $message }}</p>
          @enderror
        </div>
        

        <div class="mb-3">
    <label for="status" class="form-label h7">Status</label>
    <select id="status" name="status" class="form-control">
        <option value="active" {{ old('status', $videoLecture->status) == 'active' ? 'selected' : '' }}>InActive</option>
        <option value="inactive" {{ old('status', $videoLecture->status) == 'inactive' ? 'selected' : '' }}>active</option>
    </select>
    @error('status')
        <div class="text-danger">{{ $message }}</div>
    @enderror
</div>

        <!-- <div class="mb-3">
          <label for="created_by" class="form-label h7">Created By</label>
          <input value="{{ old('created_by') }}" type="text" class="form-control form-control-lg @error('created_by') is-invalid @enderror" placeholder="Enter Created By" name="created_by" id="created_by">
          @error('created_by')
            <p class="invalid-feedback">{{ $message }}</p>
          @enderror
        </div> -->

        <div class="d-grid">
          <button class="btn btn-lg btn-primary">Submit</button>
        </div>
      </div>
    </form>
  </div>
  <!-- /.card -->
</section>
<!-- /.content -->
@endsection
